import{a as m,S as p,i as l}from"./assets/vendor-DqB7j7Ix.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const g="47396340-f7005e76dc1b3bde31bf703a9",y="https://pixabay.com/api/";function h(r){const i={key:g,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0};return m.get(y,{params:i}).then(o=>o.data).catch(o=>{throw console.error("Error fetching images:",o),new Error("Failed to fetch images from Pixabay.")})}let s=null;function b(r){const i=document.querySelector(".gallery");if(!i){console.error("Gallery container not found.");return}const o=r.map(({largeImageURL:n,webformatURL:e,tags:t,likes:a,views:f,comments:d,downloads:u})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${n}">
            <img class="gallery-image" src="${e}" alt="${t}" />
          </a>
          <div class="image-info">
            <div class="info-item"><b>Likes</b><p>${a}</p></div>
            <div class="info-item"><b>Views</b><p>${f}</p></div>
            <div class="info-item"><b>Comments</b><p>${d}</p></div>
            <div class="info-item"><b>Downloads</b><p>${u}</p></div>
          </div>
        </li>`).join("");i.insertAdjacentHTML("beforeend",o),s?s.refresh():s=new p(".gallery a",{captionsData:"alt",captionDelay:250})}function v(){const r=document.querySelector(".gallery");r&&(r.innerHTML=""),s&&(s.destroy(),s=null)}function L(){const r=document.querySelector(".loader");r&&r.classList.add("is-visible")}function S(){const r=document.querySelector(".loader");r&&r.classList.remove("is-visible")}const c=document.querySelector(".form"),q=c.elements["search-text"];c.addEventListener("submit",async r=>{r.preventDefault();const i=q.value.trim();if(i===""){l.error({title:"Error",message:"Search field cannot be empty!",position:"topRight"});return}v(),L();try{const o=await h(i);o.hits.length===0?l.info({message:"❌ Sorry, there are no images matching your search query. Please try again!",position:"topRight",icon:!1,close:!1,backgroundColor:"#ef4040",maxWidth:"432px",minHeight:"88px",html:!0}):b(o.hits)}catch(o){l.error({title:"Error",message:o.message||"An error occurred while fetching images. Please try again later.",position:"topRight"})}finally{S(),c.reset()}});
//# sourceMappingURL=index.js.map
